### PR TITLE
Use valid SPDX short identifier

### PR DESCRIPTION
**Pull request by pathmapper**
https://spdx.org/licenses/BSD-2-Clause.html

### CODE REVIEW

**Comment by pathmapper** [comment]
A valid SPDX identifier is needed for tools like https://github.com/codepunkt/webpack-license-plugin, see https://github.com/codepunkt/webpack-license-plugin/issues/443.

**Comment by codepunkt** [comment]
More info on why a valid SPDX identifier is preferrable is available in [the npm docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license)! 😉

**Review by kepta — APPROVED** [review]

**Comment by pathmapper** [comment]
@kepta any chance getting this merged and providing a new release?

**Comment by kepta** [comment]
This was deployed in `0.8.1`.

**Comment by pathmapper** [comment]
Thanks a lot :+1:

**Pull request merged**
